steps:
  - name: "docker.io/library/python:3.10"
    entrypoint: /bin/sh
    # Run pip install and pytest in the same build step
    # (pip packages won't be preserved in future steps!)
    args: [-c, "pip install -r requirements.txt"]
    dir: ""
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "function-1",
        "--region",
        "asia-northeast1",
        "--trigger-http",
        "--runtime",
        "python310",
        "--entry-point",
        "hello_http",
      ]
    dir: ""
